# Generated by Django 4.1.4 on 2023-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='ORDID',
            field=models.CharField(default=0, max_length=20, verbose_name='訂單編號'),
        ),
    ]
