# Generated by Django 4.1.4 on 2023-01-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prefermode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEMID', models.CharField(max_length=20, verbose_name='使用者編號')),
                ('FMODE', models.CharField(max_length=20, verbose_name='FMODE')),
                ('LMODE', models.CharField(max_length=20, verbose_name='LMODE')),
                ('WMODE', models.CharField(max_length=20, verbose_name='WMODE')),
            ],
        ),
    ]
