# Generated by Django 4.1.4 on 2023-01-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_bag_ordid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='ORDID',
        ),
    ]
