# Generated by Django 4.1.5 on 2023-01-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_remove_bag_ordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='BID',
            field=models.CharField(default='0', max_length=20, verbose_name='洗衣袋編號'),
        ),
    ]
