# Generated by Django 4.1.4 on 2023-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='REPROBLEMS',
            fields=[
                ('PID', models.CharField(default='0', editable=False, max_length=43, primary_key=True, serialize=False, verbose_name='回報序號')),
                ('MEMID', models.CharField(default='', editable=False, max_length=43, verbose_name='會員序號')),
                ('ORDID', models.CharField(max_length=43, null=True, verbose_name='訂單序號')),
                ('PTYPE', models.CharField(max_length=43, null=True, verbose_name='回報類型')),
                ('PTIME', models.DateField(blank=True, null=True, verbose_name='回報時間')),
                ('PDISC', models.CharField(max_length=43, null=True, verbose_name='問題敘述')),
                ('PRE', models.CharField(max_length=43, null=True, verbose_name='處理回覆')),
                ('PDEAL', models.CharField(max_length=43, null=True, verbose_name='處理與否')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
