# Generated by Django 4.1.4 on 2023-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproblems',
            name='PID',
            field=models.CharField(default='001', editable=False, max_length=43, primary_key=True, serialize=False, verbose_name='回報序號'),
        ),
    ]
