# Generated by Django 4.1.4 on 2023-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBER',
            fields=[
                ('MEMID', models.CharField(editable=False, max_length=43, primary_key=True, serialize=False)),
                ('ACCESS', models.CharField(max_length=43)),
            ],
        ),
    ]
