# Generated by Django 4.1.4 on 2023-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MEMADDR',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='MEMBAGS',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='MEMCARD',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='MEMPHONE',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='ACCESS',
            field=models.CharField(default='', max_length=43),
        ),
    ]
