# Generated by Django 4.1.4 on 2023-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_member_memaddr_member_membags_member_memcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGREE',
            fields=[
                ('MEMID', models.CharField(editable=False, max_length=43, primary_key=True, serialize=False)),
                ('YES', models.CharField(max_length=42)),
            ],
        ),
    ]
