# Generated by Django 4.1.4 on 2023-01-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agree',
            name='YES',
        ),
    ]
