# Generated by Django 4.1.4 on 2023-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_agree_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MEMBAG',
            field=models.IntegerField(default=1),
        ),
    ]
