# Generated by Django 4.1.4 on 2023-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_member_membag'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='USINGBAG',
            field=models.IntegerField(default=0),
        ),
    ]
