# Generated by Django 4.1.4 on 2023-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_member_usingbag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='MEMBAG',
        ),
        migrations.AlterField(
            model_name='member',
            name='MEMBAGS',
            field=models.IntegerField(default=1),
        ),
    ]
