# Generated by Django 4.1.5 on 2023-01-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_member_membag_alter_member_membags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ACCESS',
            field=models.CharField(default='DEFAULT', max_length=43),
        ),
        migrations.AlterField(
            model_name='member',
            name='MEMADDR',
            field=models.CharField(default='DEFAULT', max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='MEMBAGS',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='MEMCARD',
            field=models.CharField(default='DEFAULT', max_length=19),
        ),
        migrations.AlterField(
            model_name='member',
            name='MEMPHONE',
            field=models.CharField(default='DEFAULT', max_length=12),
        ),
    ]
