# Generated by Django 4.1.4 on 2023-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='WHICHCOLOR',
            field=models.IntegerField(verbose_name='COLOR'),
        ),
    ]
